export const ENGLISH_PROMPT = [
  "On the occasion of Vietnam Teachers' Day 20/11, we wish you much joy and health, and may you always have confidence and success in your noble career of nurturing people.",
  "On the occasion of Vietnam Teachers' Day 20/11, we would like to send our wishes for health and success to you, who have guided us to the shores of knowledge.",
  "Today, on the Charter Day of Teachers 20/11, we wish you success and abundant happiness on this holiday and in your life, training many excellent and outstanding generations of students.",
  "You are a vast ocean of knowledge; thank you for dedicating yourself to the education career, teaching us and countless generations of successful students. We wish you health to continue this noble career.",
  "On Vietnam Teachers' Day, with all our sincerity, we want to send you our wishes for a life always filled with joy, and may you encounter good fortune on this noble career path.",
  "On 20/11, we wish you always to be the lighthouse guiding us, illuminating our path, and forever be the ferryman bringing us to the shores of knowledge.",
  "Thank you for igniting the flame of knowledge in us, enriching our source of knowledge, and opening the path of hope. We wish you increasing success on the path of nurturing people.",
  "We wish you all the best, with this heartfelt sentiment, sending you wishes for success, health, and happiness in life.",
  "Wishing our beloved teacher abundant health, enough heart and intellect to sow knowledge for students, and to create dedicated individuals to build the country.",
  "On 20/10, Vietnam Teachers' Day, we sincerely thank you for guiding us closer to the shores of knowledge. We wish you health, success, and happiness in life.",
  "Dear teacher, today is a special and meaningful day. We wish you increasing health, joy, and love for life.",
  "Thank you for guiding us from our first steps, for showing us the path of knowledge. We wish you a fulfilling and happy life.",
  "Another Charter season has come, we wish you much health, much happiness in life, and success in your career.",
  "November has arrived, and on this beloved 20th, happy Charter Day! We wish you much health and success in guiding us to become good students.",
  "Another 20/11 season has come; we wish you abundant health, always youthful and cheerful, forever a teacher who lights our path.",
  "On the occasion of 20/11, we wish you the best wishes. May you fulfill your noble mission in the century-long career of nurturing people and in the country's renewal process. We sincerely thank you.",
  "We wish you always good health, youthfulness, cheerfulness, and unwavering faith while increasingly enhancing your courage before mischievous students like us. Happy Vietnam’s Teacher Day!",
  'If asked: Where does success come from? We would answer: "It is you, teacher, who has brought us knowledge, the luggage to step into life."',
  "Forever echoing in us are your words. It feels like yesterday, though it has long passed. Your lessons are like wings for dreams, allowing us to soar beyond the fairytale skies.",
  "The debt of teaching is higher than mountains, the meaning of teachers is like the vast sea, the work of parents is always engraved in our hearts, and the gratitude for teachers will forever remain. On Vietnam Teachers' Day, we wish you health and success in your nurturing career.",
  "Dear teacher! You are a gentle mother, nurturing hope in our hearts, cultivating civilization by the cradle, dispelling ignorance, and bringing us wisdom, carefully carving each beautiful aspect of our souls...",
  "The teaching profession is the noblest of all. On the occasion of Vietnam Teachers' Day, we cannot express more than to wish you always joyfully and healthily continue guiding and teaching us valuable lessons.",
  '"One word is a teacher, half a word is a teacher." On the occasion of 20/11, we wish you health, happiness, and much success in your nurturing career.',
  "Dear teacher, when you read these wishes, just know that this unnamed student wants to send you wishes for health and success in life as well as in your nurturing career. A thank you may not be enough for what you have done for us. We wish you always good health, youthfulness, cheerfulness, and success in your teaching career.",
  'Happy Vietnam Teachers\' Day 20/11! We wish you always enough heart, mind, and strength to contribute even more to the "nurturing people" career!',
  "Thank you for the knowledge and energy you bring to us in class. We will always cherish these things.",
  "Life is a long journey, and you are the ones who always accompany us on the path of knowledge. Thank you for guiding and supporting us on this difficult and bumpy road.",
  "On the occasion of 20/11, we can only express our deep gratitude to you. We hope you always maintain good health to fulfill your nurturing career well.",
  "Your interesting and engaging lessons always open up a colorful world for us. On the occasion of 20/11, we wish all the best things will come to you.",
  "With each year completing the ferrying of generations across the river, your hair turns more gray. May you always maintain your health to continue guiding many more ferries to the shore.",
  "Even from afar, we still wish to send our best wishes and respect to you.",
  "Thank you for being the one who gives us wings, guiding us closer to our dreams so that we can achieve the success we have today.",
  "In the journey of life, thank you for expanding our knowledge, bringing our lives to the light of hope. Thank you with all our respect.",
  "You are like a second mother or father, supporting us in difficult and confusing times on our journey to maturity. Thank you and wish you all the best.",
  "On the occasion of 20/11, we wish you always good health and happiness to continue providing many valuable lessons and knowledge.",
  "May good things always come to you. We hope you continue to succeed and be loved by even more students on your teaching journey.",
  "The teaching profession has always been the noblest and most respected profession. We hope you will always be healthy and cheerful to continue accompanying us on the path of knowledge.",
  "We wish you receive many flowers and gifts on 20/11 and have plenty of joyful smiles.",
  "Even though we have grown up, we still cherish your teachings. We send our deepest gratitude to you.",
];

export const VIETNAMESE_PROMPT = [
  "Nhân ngày Nhà giáo Việt Nam 20/11 chúng con kính chúc thầy/cô có thật nhiều niềm vui, sức khoẻ, chúc cho thầy/cô luôn vững tin và thành công trên sự nghiệp trồng người.",
  "Nhân dịp ngày Nhà giáo Việt Nam 20/11, chúng con xin gửi lời chúc sức khỏe, lời chúc thành công đến thầy/cô, người dìu dắt chúng con đến với bến bờ tri thức.",
  "Hôm nay, ngày Hiến chương Nhà giáo 20/11, chúng con chúc thầy/cô trong ngày lễ này và cuộc sống của thầy/cô luôn thành công, hạnh phúc ngập tràn, đào tạo ra nhiều thế hệ học trò xuất sắc và ưu tú.",
  "Thầy/cô là một biển lớn của tri thức, cảm ơn thầy/cô đã cống hiến cho sự nghiệp giáo dục, dạy dỗ chúng con và biết bao thế hệ học sinh thành tài, chúc thầy/cô sức khỏe để tiếp tục sự nghiệp cao cả này.",
  "Nhân ngày Nhà giáo Việt Nam, với cả tấm chân tình này mà chúng con muốn gửi tới thầy/cô, chúc cho thầy/cô trong cuộc sống luôn luôn tràn ngập niềm vui, luôn gặp may mắn trên con đường sự nghiệp cao cả này.",
  "Ngày 20/11, chúc thầy/cô mãi là ngọn hải đăng chỉ đường, dẫn lối, soi sáng con đường của chúng con, mãi là những người lái đò đưa chúng con đến với bến bờ của tri thức.",
  "Cảm ơn thầy/cô đã nhóm lên cho chúng con ngọn lửa ánh sáng của tri thức, làm phong phú thêm nguồn tri thức trong chúng con, mở lối mà ánh sáng hy vọng, chúc thầy/cô ngày càng thành công trên con đường trồng người.",
  "Chúng con chúc thầy/cô tất cả, với tấm chân tình này, muốn gửi tới thầy/cô lời chúc thành đạt, lời chúc sức khỏe, lời chúc hạnh phúc trong cuộc sống.",
  "Chúc thầy/cô yêu quý của chúng con dồi dào sức khỏe, có đủ tâm, trí lực để gieo con chữ cho học sinh, kiến tạo nên những con người cống hiến xây dựng đất nước.",
  "Ngày 20/10 ngày Nhà giáo Việt Nam, chúng con xin gửi lời cảm ơn chân thành tới thầy/cô đã dìu dắt chúng con gần hơn đối với bến bờ tri thức, chúc thầy/cô sức khỏe, thành công và hạnh phúc trong cuộc sống.",
  "Thầy/cô ơi, ngày hôm nay là một ngày đặc biệt và ý nghĩa, chúng con chúc thầy/cô ngày càng mạnh khỏe, vui vẻ và yêu đời.",
  "Cảm ơn thầy/cô, người đã dìu dắt chúng con đi từ những bước chân chập chững, người đã dẫn lối con đường tri thức cho chúng con, chúc thầy/cô cuộc sống viên mãn và hạnh phúc.",
  "Một mùa Hiến chương nữa lại về, chúng con xin chúc thầy/cô thật nhiều sức khỏe, thật nhiều hạnh phúc trong cuộc sống, cũng như thành công trong sự nghiệp.",
  "Tháng 11 đã đến ngày 20 thân thương, chúc mừng ngày Hiến chương, chúc thầy/cô thật nhiều sức khỏe, công tác tốt dìu dắt chúng con thành con ngon trò giỏi.",
  "Lại một mùa 20/11 đã đến, chúng con chúc thầy/cô có thật nhiều sức khỏe, luôn trẻ trung vui tươi mãi là một người thầy/cô, người chỉ đường dẫn lối soi sáng con đường cho chúng con.",
  "Nhân ngày 20/11, chúng con xin chúc thầy/cô lời chúc tốt đẹp nhất. Chúc thầy/cô hoàn thành nhiệm vụ cao cả của mình trong sự nghiệp trăm năm trồng người, trong công cuộc đổi mới của đất nước. Chúng con chân thành cảm ơn thầy/cô.",
  "Chúng con chúc thầy/cô luôn mạnh khoẻ, trẻ trung, vui tính, luôn luôn giữ vững niềm tin và ngày càng nâng cao sự dũng cảm trước những đứa học trò nghịch như quỷ sứ bọn chúng con. Happy Vietnam’s Teacher Day.",
  "Nếu được hỏi: Thành công bắt nguồn từ đâu? Chúng con sẽ trả lời rằng: “Là thầy/cô - người đã mang đến cho chúng con kiến thức, hành trang bước vào đời”.",
  "Mãi mãi bên chúng con tiếng của thầy/cô vang vọng. Đã xa rồi mà chúng con ngỡ hôm qua. Bài giảng của thầy/cô như chắp cánh ước mơ, cho chúng con bay khỏi vùng trời cổ tích.",
  "Ơn dạy dỗ cao dường hơn núi, nghĩa thầy/cô như nước biển khơi, công cha mẹ chúng con luôn tạc dạ, ơn thầy/cô chúng con mãi ghi lòng. Nhân ngày nhà giáo Việt Nam chúng con xin kính chúc thầy/cô mạnh khỏe, thành công trong sự nghiệp trồng người.",
  "Cô ơi! Cô là người mẹ hiền từ, nuôi dưỡng trong lòng chúng con niềm hy vọng, bồi dưỡng văn minh bên cánh nôi, xua đi những ngu muội, mang đến cho chúng con trí tuệ, tỉ mỉ chạm khắc từng nét đẹp tâm hồn…",
  "Nghề giáo là nghề cao quý nhất trong các nghề. Nhân dịp ngày Nhà giáo Việt Nam, chúng con không biết nói gì hơn ngoài chúc thầy/cô luôn vui tươi, khỏe mạnh để tiếp tục sự nghiệp dìu dắt, dạy bảo chúng con những bài học bổ ích.",
  '"Một chữ cũng là thầy/cô, nửa chữ cũng là thầy/cô". Nhân ngày 20/11, chúng con chúc thầy/cô luôn mạnh khỏe, hạnh phúc và gặt hái được nhiều thành công trong sự nghiệp trồng người.',
  "Thầy/cô à, khi đọc được những lời chúc này, thầy/cô chỉ cần biết rằng đứa học trò giấu tên này chỉ muốn gửi tới thầy/cô những lời chúc sức khỏe, và thành công trong cuộc sống cũng như sự nghiệp trồng người. Một lời cảm ơn có lẽ là không đủ so với những gì mà thầy/cô đã làm cho chúng con. Chúng con chúc thầy/cô luôn mạnh khỏe, trẻ trung, vui tính, và thành công trong sự nghiệp nhà giáo của mình thầy/cô nhé.",
  "Chúc mừng thầy/cô nhân ngày Nhà giáo Việt Nam 20/11. Chúc thầy/cô luôn đủ tâm - trí - lực để ngày càng cống hiến nhiều hơn nữa cho sự nghiệp “trồng người”!",
  "Cảm ơn thầy/cô vì những kiến thức cũng như nguồn năng lượng mà thầy/cô mang đến những khi tới lớp. Chúng con sẽ luôn trân trọng những điều này.",
  "Cuộc sống là một hành trình dài và thầy/cô là những người luôn đồng hành cùng chúng con trên đoạn đường tri thức. Cảm ơn vì đã dẫn dắt, nâng đỡ chúng con trên đoạn đường khó khăn, gập ghềnh này.",
  "Nhân dịp 20/11 chúng con cũng không biết nói gì hơn ngoài lời cảm ơn sâu sắc đến thầy/cô. Mong thầy/cô luôn giữ gìn sức khỏe để luôn hoàn thành tốt sự nghiệp trồng người.",
  "Những bài giảng thú vị hấp dẫn của thầy/cô luôn mở ra một thế giới đầy sắc màu cho chúng con. Nhân dịp 20/11 chúng con chúc mọi điều tốt lành sẽ đến với thầy/cô.",
  "Qua mỗi năm hoàn thành chuyến đò đưa bao thế hệ qua sông, tóc thầy/cô lại điểm thêm bạc. Mong rằng thầy/cô luôn giữ gìn sức khỏe để tiếp tục giữ vững tay chèo đưa những thêm nhiều chuyến đò cập bến.",
  "Dù đang ở nơi xa nhưng chúng con vẫn xin gửi những lời chúc tốt đẹp và sự kính trọng đến thầy/cô.",
  "Cảm ơn thầy/cô vì đã là người chắp cánh, dẫn dắt cho chúng con đến gần ước mơ để chúng con có thể có thành công được như hôm nay.",
  "Trong hành trình cuộc đời, cảm ơn thầy/cô đã mở mang tri thức, đưa cuộc sống của chúng con tới ánh sáng hy vọng. Xin cảm ơn thầy/cô với tất cả sự kính trọng.",
  "Thầy/cô như người mẹ, người cha thứ hai nâng đỡ chúng con những lúc khó khăn, hoang mang trên hành trình trưởng thành của mình. Cảm ơn và chúc thầy/cô những điều tốt đẹp nhất.",
  "Nhân dịp 20/11 chúc thầy/cô luôn mạnh khỏe hạnh phúc để tiếp tục mang đến nhiều bài học hay và kiến thức bổ ích.",
  "Chúc những điều tốt đẹp sẽ luôn đến với thầy/cô. Mong rằng thầy/cô luôn thành công và được nhiều học sinh yêu mến hơn nữa trên con đường giảng dạy của mình.",
  "Nghề nhà giáo bao đời luôn là nghề cao quý và được kính trọng nhất. Mong rằng thầy/cô sẽ luôn mạnh khỏe, vui tươi để tiếp tục đồng hành cùng chúng con trên con đường tri thức.",
  "Chúc thầy/cô trong ngày 20/11 sẽ nhận được nhiều hoa, quà và có những nụ cười thả ga nhé.",
  "Dẫu đã lớn khôn nhưng chúng con vẫn luôn khắc ghi những lời dạy của thầy/cô. Xin gửi tới thầy/cô lời tri ân sâu sắc nhất.",
];
